apiVersion: apps/v1
kind: Deployment
metadata:
  name: chemquote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chemquote
  template:
    metadata:
      labels:
        app: chemquote
    spec:
      containers:
      - name: chemquote
        image: nginxdemos/hello:plain-text
        ports:
        - containerPort: 80
