# Development Dockerfile for Vite

# Use the official Node.js image with the specified version
FROM node:22.9.0

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json first
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Expose the port that Vite runs on  - Default Vite port
EXPOSE 5173  

# Command to run Vite in development mode
CMD ["npm", "run", "dev"]
