version: '3.8'

services:
  python-api:
    build:
      context: ..  # Set the context to the parent directory (project root)
      dockerfile: infrastructure/Dockerfile  # Specify the Dockerfile path
    ports:
      - "5001:5000"
    depends_on:
      - chemquote-db-host
    environment:
      DB_HOST: ${DB_HOST}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_USER: ${DB_USER}
      DB_NAME: ${DB_NAME}
      FLASK_ENV: ${FLASK_ENV}
    volumes:
      - ..:/app  # Mount the project root to /app in the container

  chemquote-db-host:
    image: mysql:8.4.2
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: ${DB_HOST}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    depends_on:
      - chemquote-db-host

volumes:
  mysql_data:
